// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://injeupysvbejrdfyqjwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluamV1cHlzdmJlanJkZnlxandtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTkyOTMsImV4cCI6MjA2ODc3NTI5M30.ljfYAAnPgX6Kn3xqOTefrRc9-_rq7Ub6jbXO7kTCCRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});